"""Render an audit result as text, JSON, or Markdown.

The report is the product: an environment builder should be able to read the top
line in one second (ROBUST / HACKABLE / INCONCLUSIVE) and hand the Markdown to a
colleague as evidence. Every finding names the weakness and its fix, so the
report is a to-do list, not just a verdict.
"""

from __future__ import annotations

import json

from .audit import AuditResult
from .version import __version__

_VERDICT_LINE = {
    "ROBUST": "ROBUST - the grader rejected every non-solution in the catalog.",
    "HACKABLE": "HACKABLE - the grader accepted at least one non-solution.",
    "INCONCLUSIVE": "INCONCLUSIVE - the grader baseline could not be trusted.",
}


def to_json(result: AuditResult) -> str:
    payload = {
        "tool": "vigil-probe",
        "version": __version__,
        "task": {"id": result.spec_id, "name": result.spec_name},
        "verdict": result.verdict,
        "network_isolation": result.isolation,
        "grader_topology": result.topology,
        "reset_paths_applied": list(result.reset_paths),
        "reference_solution": {"checked": result.reference_ok is not None,
                               "passes": result.reference_ok,
                               "note": result.reference_note},
        "probes": [
            {
                "id": o.probe.id,
                "title": o.probe.title,
                "severity": o.probe.severity,
                "grader_passed": o.grader_passed,
                "finding": o.is_finding,
                "detail": o.grade_reason,
                "counts": o.counts,
                "error": o.error,
                "weakness": o.probe.weakness,
                "remediation": o.probe.remediation,
                "sources": list(o.probe.sources),
            }
            for o in result.outcomes
        ],
        "findings": [o.probe.id for o in result.findings],
    }
    return json.dumps(payload, indent=2)


def to_text(result: AuditResult) -> str:
    lines = [
        f"vigil-probe {__version__}  ({result.isolation} network isolation)",
        f"Task: {result.spec_id}  {result.spec_name}",
        "",
        f"Verdict: {_VERDICT_LINE.get(result.verdict, result.verdict)}",
        f"Grader topology: {result.topology}",
        f"Grade-time resets: {', '.join(result.reset_paths) if result.reset_paths else 'none declared'}",
        f"Reference solution: {result.reference_note}",
        "",
    ]
    for o in result.outcomes:
        if o.error:
            mark, tail = "ERROR", f"probe error: {o.error}"
        elif o.is_finding:
            mark, tail = "FINDING", o.grade_reason
        else:
            mark, tail = "ok", o.grade_reason
        lines.append(f"  [{mark:^8}] {o.probe.id:<26} {o.probe.severity:<8} {tail}")
    findings = result.findings
    if findings:
        lines += ["", "Fix these:"]
        for o in findings:
            lines += [f"  * {o.probe.title}", f"      {o.probe.remediation}"]
    return "\n".join(lines) + "\n"


def to_markdown(result: AuditResult) -> str:
    badge = {"ROBUST": "PASS", "HACKABLE": "FAIL", "INCONCLUSIVE": "INCONCLUSIVE"}[result.verdict]
    out = [
        f"# vigil-probe report: `{result.spec_id}`",
        "",
        f"**Verdict: {badge} ({result.verdict})** &middot; {result.spec_name}",
        "",
        f"- Network isolation during grading: `{result.isolation}`",
        f"- Grader topology: `{result.topology}`",
        f"- Grade-time resets: {('`' + '`, `'.join(result.reset_paths) + '`') if result.reset_paths else '_none declared_'}",
        f"- Reference solution: {result.reference_note}",
        f"- Probes run: {len(result.outcomes)} &middot; Findings: {len(result.findings)}",
        "",
        "| Probe | Severity | Grader passed non-solution? | Finding |",
        "|---|---|---|---|",
    ]
    for o in result.outcomes:
        passed = "yes" if o.grader_passed else "no"
        finding = "**yes**" if o.is_finding else "no"
        if o.error:
            passed, finding = "error", "-"
        out.append(f"| {o.probe.id} | {o.probe.severity} | {passed} | {finding} |")
    if result.findings:
        out += ["", "## Findings and fixes", ""]
        for o in result.findings:
            out += [
                f"### {o.probe.title} (`{o.probe.id}`, {o.probe.severity})",
                "",
                f"**Weakness.** {o.probe.weakness}",
                "",
                f"**Fix.** {o.probe.remediation}",
                "",
                "**Documented in:** " + "; ".join(o.probe.sources),
                "",
            ]
    else:
        out += ["", "No findings. The grader rejected every non-solution in the catalog.", ""]
    out += ["---", "_Generated by vigil-probe, part of Agent Vigil._"]
    return "\n".join(out) + "\n"


def render(result: AuditResult, fmt: str) -> str:
    if fmt == "json":
        return to_json(result)
    if fmt == "markdown":
        return to_markdown(result)
    return to_text(result)
